<a href="https://colab.research.google.com/github/GirishNaik711/Customer_Churn_Analysis/blob/main/Churn_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install -U scikit-learn imbalanced-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 73.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 kB 20.5 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
  Attempting uninstall: imbalanced-learn
    Found existing installation: imbalanced-learn 0.10.1
    Uninstalling imbalanced-learn-0.10.1:
      Successfully uninstalled imbalanced-learn-0.10.1


In [ ]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [ ]:
df = pd.read_csv('/content/Tel__churn_eda.csv')
df.head(2)

Unnamed: 0  SeniorCitizen  MonthlyCharges  TotalCharges  Churn  \
0           0              0           29.85         29.85      0   
1           1              0           56.95       1889.50      0   

   gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  ...  \
0              1            0           0            1              1  ...   
1              0            1           1            0              1  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   

   PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                           0                    1                     0   
1                           1                    0                     0   

   tenure_group_25 - 36  tenure_group_37 - 48  tenure_group_49 - 60  \
0                     0                     0                     0   
1                     1                     0                     0   

   tenure_group_61 - 72  
0                     0  
1                     0  

[2 rows x 52 columns]

In [ ]:
df = df.drop('Unnamed: 0', axis = 1)
df.head()

SeniorCitizen  MonthlyCharges  TotalCharges  Churn  gender_Female  \
0              0           29.85         29.85      0              1   
1              0           56.95       1889.50      0              0   
2              0           53.85        108.15      1              0   
3              0           42.30       1840.75      0              0   
4              0           70.70        151.65      1              1   

   gender_Male  Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  ...  \
0            0           0            1              1               0  ...   
1            1           1            0              1               0  ...   
2            1           1            0              1               0  ...   
3            1           1            0              1               0  ...   
4            0           1            0              1               0  ...   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                           0                    1                     0   
1                           1                    0                     0   
2                           1                    1                     0   
3                           0                    0                     0   
4                           0                    1                     0   

   tenure_group_25 - 36  tenure_group_37 - 48  tenure_group_49 - 60  \
0                     0                     0                     0   
1                     1                     0                     0   
2                     0                     0                     0   
3                     0                     1                     0   
4                     0                     0                     0   

   tenure_group_61 - 72  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 51 columns]

In [ ]:
x = df.drop('Churn', axis = 1)
x

SeniorCitizen  MonthlyCharges  TotalCharges  gender_Female  gender_Male  \
0                 0           29.85         29.85              1            0   
1                 0           56.95       1889.50              0            1   
2                 0           53.85        108.15              0            1   
3                 0           42.30       1840.75              0            1   
4                 0           70.70        151.65              1            0   
...             ...             ...           ...            ...          ...   
7027              0           84.80       1990.50              0            1   
7028              0          103.20       7362.90              1            0   
7029              0           29.60        346.45              1            0   
7030              1           74.40        306.60              0            1   
7031              0          105.65       6844.50              0            1   

      Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  PhoneService_No  \
0              0            1              1               0                1   
1              1            0              1               0                0   
2              1            0              1               0                0   
3              1            0              1               0                1   
4              1            0              1               0                0   
...          ...          ...            ...             ...              ...   
7027           0            1              0               1                0   
7028           0            1              0               1                0   
7029           0            1              0               1                1   
7030           0            1              1               0                0   
7031           1            0              1               0                0   

      ...  PaymentMethod_Bank transfer (automatic)  \
0     ...                                        0   
1     ...                                        0   
2     ...                                        0   
3     ...                                        1   
4     ...                                        0   
...   ...                                      ...   
7027  ...                                        0   
7028  ...                                        0   
7029  ...                                        0   
7030  ...                                        0   
7031  ...                                        1   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                         0                               1   
1                                         0                               0   
2                                         0                               0   
3                                         0                               0   
4                                         0                               1   
...                                     ...                             ...   
7027                                      0                               0   
7028                                      1                               0   
7029                                      0                               1   
7030                                      0                               0   
7031                                      0                               0   

      PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24  \
0                              0                    1                     0   
1                              1                    0                     0   
2                              1                    1                     0   
3                              0                    0                     0   
4                              0                    1              

In [ ]:
y = df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

#Decision Tree Classifier

In [ ]:
dt_model = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)
dt_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [ ]:
dt_y_pred = dt_model.predict(x_test)
dt_y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
dt_model.score(x_test, y_test)

0.7761194029850746

In [ ]:
print(classification_report(y_test, dt_y_pred))

              precision    recall  f1-score   support

           0       0.84      0.86      0.85      1028
           1       0.59      0.54      0.57       379

    accuracy                           0.78      1407
   macro avg       0.71      0.70      0.71      1407
weighted avg       0.77      0.78      0.77      1407



As you can see that the accuracy is quite low, and as it's an imbalanced dataset, we shouldn't consider Accuracy as our metrics to measure the model, as Accuracy is cursed in imbalanced datasets.
Hence, we need to check recall, precision & f1 score for the minority class, and it's quite evident that the precision, recall & f1 score is too low for Class 1, i.e. churned customers.
Hence, moving ahead to call SMOTEENN (UpSampling + ENN)

In [ ]:
sm = SMOTEENN()
x_sampled, y_sampled = sm.fit_resample(x,y)

In [ ]:
xr_train, xr_test, yr_train, yr_test = train_test_split(x_sampled, y_sampled, test_size = 0.2)

In [ ]:
dt_model_r = DecisionTreeClassifier(criterion = 'gini', random_state = 100, max_depth = 6, min_samples_leaf = 8)

In [ ]:
dt_model_r.fit(xr_train, yr_train)
dt_yr_pred = dt_model_r.predict(xr_test)
dt_r_score = dt_model_r.score(xr_test, yr_test)
print(f'Score: {dt_r_score} \n')
print(f'Report\n{classification_report(yr_test, dt_yr_pred)}')
print(f'Matrix: \n{confusion_matrix(yr_test, dt_yr_pred)}')

Score: 0.9224872231686542 

Report
              precision    recall  f1-score   support

           0       0.91      0.91      0.91       516
           1       0.93      0.93      0.93       658

    accuracy                           0.92      1174
   macro avg       0.92      0.92      0.92      1174
weighted avg       0.92      0.92      0.92      1174

Matrix: 
[[470  46]
 [ 45 613]]


Now we can see quite better results w.r.t minority class

#Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_model = RandomForestClassifier(n_estimators = 100, criterion = 'gini', max_depth = 6, min_samples_leaf = 8, random_state = 100)

In [ ]:
rf_model.fit(x_train, y_train)
rf_y_pred = rf_model.predict(x_test)

In [ ]:
print(f'Score: {rf_model.score(x_test, y_test)}\n')
print(f'Report: \n{classification_report(y_test, rf_y_pred)}')
print(f'Matrix: \n{confusion_matrix(y_test, rf_y_pred)}')

Score: 0.7860696517412935

Report: 
              precision    recall  f1-score   support

           0       0.81      0.92      0.86      1028
           1       0.65      0.44      0.52       379

    accuracy                           0.79      1407
   macro avg       0.73      0.68      0.69      1407
weighted avg       0.77      0.79      0.77      1407

Matrix: 
[[941  87]
 [214 165]]


In [ ]:
sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)


In [ ]:
rf_model_r = RandomForestClassifier(n_estimators = 100, criterion = 'gini', max_depth = 6, min_samples_leaf = 8, random_state = 100)

In [ ]:
rf_model_r.fit(xr_train1, yr_train1)
rf_yr_pred1 = rf_model.predict(xr_test1)

In [ ]:
print(f'Score: {rf_model_r.score(xr_test1, yr_test1)}\n')
print(f'Report: \n{classification_report(yr_test1, rf_yr_pred1)}')
print(f'Matrix: \n{confusion_matrix(yr_test1, rf_yr_pred1)}')

Score: 0.9289340101522843

Report: 
              precision    recall  f1-score   support

           0       0.63      0.99      0.77       523
           1       0.98      0.53      0.69       659

    accuracy                           0.73      1182
   macro avg       0.80      0.76      0.73      1182
weighted avg       0.82      0.73      0.72      1182

Matrix: 
[[516   7]
 [307 352]]


With RF Classifier, also we are able to get quite good results, infact better than Decision Tree.

#PCA

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train)
xr_test_pca = pca.transform(xr_test)
explained_variance = pca.explained_variance_ratio_

In [ ]:
rf_model_pca = RandomForestClassifier(n_estimators = 100, criterion = 'gini', max_depth = 6, min_samples_leaf = 8, random_state = 100)
rf_model_pca.fit(xr_train_pca, yr_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [ ]:
yr_pca_pred = rf_model_pca.predict(xr_test_pca)

In [ ]:
print(f'Score: {rf_model_pca.score(xr_test_pca, yr_test)}\n')
print(f'Report: \n{classification_report(yr_test, yr_pca_pred)}')
print(f'Matrix: \n{confusion_matrix(yr_test, yr_pca_pred)}')

Score: 0.7163543441226575

Report: 
              precision    recall  f1-score   support

           0       0.73      0.56      0.64       516
           1       0.71      0.84      0.77       658

    accuracy                           0.72      1174
   macro avg       0.72      0.70      0.70      1174
weighted avg       0.72      0.72      0.71      1174

Matrix: 
[[291 225]
 [108 550]]


With PCA, we couldn't see any better results, hence let's finalize the model which was created by RF Classifier, and save the model.

#Pickling the Model

In [ ]:
import pickle

In [ ]:
filename = 'model.sav'
pickle.dump(rf_model_r, open(filename, 'wb'))

In [ ]:
load_model = pickle.load(open(filename, 'rb'))

In [ ]:
print(f'Score: {load_model.score(xr_test, yr_test)}')

Score: 0.9361158432708688
